apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace.name }}
data:
  APP_ENV: {{ .Values.app.env | quote }}
  MESSAGE: {{ .Values.app.message | quote }}
  APP_VERSION: {{ .Values.app.version | quote }}