apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  APP_ENV: {{ .Values.app.env | quote }}
  MESSAGE: {{ .Values.app.message | quote }}
  APP_READY: {{ .Values.app.ready | quote }}
  APP_VERSION: {{ .Values.app.version | quote }}