apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api
  namespace: my-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
        - name: my-api
          image: my-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: my-api-config
                  key: APP_ENV
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: my-api-config
                  key: MESSAGE
            - name: SECRET_MESSAGE
              valueFrom:
                secretKeyRef:
                  name: my-api-secret
                  key: SECRET_MESSAGE

          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /healthz/live
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"